-- Authored calendar only. No production data. Apply to SABLY_DB development after migration.sql.
INSERT OR IGNORE INTO promocion (id,nombre,activa,pct,cupon,titular,proveedores,incluir,excluir,paises,desde,hasta,prioridad,url_key,tema,etiqueta,por) VALUES ('bf-2026','Black Friday',1,50,'031016','El descuento más grande del año','["masterclasses"]','[]','[]','[]',1795651200,1796083200,100,'','blackFriday','Black Friday','migration:calendar');
INSERT OR IGNORE INTO promocion (id,nombre,activa,pct,cupon,titular,proveedores,incluir,excluir,paises,desde,hasta,prioridad,url_key,tema,etiqueta,por) VALUES ('navidad-2026','Navidad',1,50,'031016','Regálate un oficio nuevo','["masterclasses"]','[]','[]','[]',1797310800,1798261200,90,'','navidad','Navidad','migration:calendar');
INSERT OR IGNORE INTO promocion (id,nombre,activa,pct,cupon,titular,proveedores,incluir,excluir,paises,desde,hasta,prioridad,url_key,tema,etiqueta,por) VALUES ('buen-fin-mx-2026','El Buen Fin',1,50,'031016','El Buen Fin en Sably','["masterclasses"]','[]','[]','["mx"]',1794549600,1794895200,85,'','blackFriday','El Buen Fin','migration:calendar');
INSERT OR IGNORE INTO promocion (id,nombre,activa,pct,cupon,titular,proveedores,incluir,excluir,paises,desde,hasta,prioridad,url_key,tema,etiqueta,por) VALUES ('amor-amistad-co-2026','Amor y Amistad',1,50,'031016','Regala algo que dure','["masterclasses"]','[]','[]','["co"]',1789362000,1789880400,80,'','amor','Amor y Amistad','migration:calendar');
INSERT OR IGNORE INTO promocion (id,nombre,activa,pct,cupon,titular,proveedores,incluir,excluir,paises,desde,hasta,prioridad,url_key,tema,etiqueta,por) VALUES ('regreso-clases-2026','Vuelta a clases',1,25,'010775','Empieza el semestre con un oficio','["masterclasses"]','[]','[]','[]',1786770000,1787634000,50,'','clases','Vuelta a clases','migration:calendar');
INSERT OR IGNORE INTO promocion (id,nombre,activa,pct,cupon,titular,proveedores,incluir,excluir,paises,desde,hasta,prioridad,url_key,tema,etiqueta,por) VALUES ('cyber-cl-pe-2026','CyberDay',1,25,'010775','Solo durante el CyberDay','["masterclasses"]','[]','[]','["cl","pe"]',1791176400,1791522000,55,'','cyber','CyberDay','migration:calendar');
INSERT OR IGNORE INTO promocion (id,nombre,activa,pct,cupon,titular,proveedores,incluir,excluir,paises,desde,hasta,prioridad,url_key,tema,etiqueta,por) VALUES ('ano-nuevo-2027','Propósitos de Año Nuevo',1,25,'010775','Este año sí aprendes el oficio','["masterclasses"]','[]','[]','[]',1798866000,1800075600,50,'','anoNuevo','Propósitos de Año Nuevo','migration:calendar');
INSERT OR IGNORE INTO promocion (id,nombre,activa,pct,cupon,titular,proveedores,incluir,excluir,paises,desde,hasta,prioridad,url_key,tema,etiqueta,por) VALUES ('dia-madre-2027','Día de la Madre',1,25,'010775','Para ella, algo que le dé ingresos','["masterclasses"]','[]','[]','["co","mx"]',1809493200,1810011600,55,'','madre','Día de la Madre','migration:calendar');
INSERT OR IGNORE INTO promocion (id,nombre,activa,pct,cupon,titular,proveedores,incluir,excluir,paises,desde,hasta,prioridad,url_key,tema,etiqueta,por) VALUES ('hot-sale-2027','Hot Sale',1,25,'010775','Hot Sale: los días de más descuento','["masterclasses"]','[]','[]','["ar","mx"]',1810530000,1811134800,55,'','cyber','Hot Sale','migration:calendar');
INSERT OR IGNORE INTO promocion (id,nombre,activa,pct,cupon,titular,proveedores,incluir,excluir,paises,desde,hasta,prioridad,url_key,tema,etiqueta,por) VALUES ('ads-25','Oferta para ti',1,25,'010775','Tu descuento está activo','["masterclasses"]','[]','[]','[]',1785560400,1814417999,20,'ads','medio','Oferta para ti','migration:calendar');
INSERT OR IGNORE INTO promocion (id,nombre,activa,pct,cupon,titular,proveedores,incluir,excluir,paises,desde,hasta,prioridad,url_key,tema,etiqueta,por) VALUES ('ads-50','Oferta especial',1,50,'031016','Tu descuento está activo','["masterclasses"]','[]','[]','[]',1785560400,1814417999,25,'ads50','maximo','Oferta especial','migration:calendar');
