name: CI Pipeline

on:
  pull_request:
    branches: [develop, main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - run: npm ci
      - name: Type-check (astro check)
        run: npm run check
      - name: Build
        run: npm run build
      - name: Validar commits (Conventional Commits)
        run: |
          npm i -D @commitlint/cli @commitlint/config-conventional --no-save
          npx commitlint --from=${{ github.event.pull_request.base.sha }} --to=${{ github.event.pull_request.head.sha }} --verbose
